trying caching again

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,6 +5,7 @@ branches:
     - master
     - model
     - gui-implementation
+    - registration-algo-dev
 
 matrix:
   include:
@@ -13,8 +14,10 @@ matrix:
       osx_image: xcode11.6
       cache:
         directories:
+          - $TRAVIS_BUILD_DIR/target
           - $HOME/Library/Caches/Homebrew
           - /usr/local/Homebrew
+          - $HOME/local_bottle_metadata
       addons:
         homebrew:
           update: true
@@ -27,11 +30,33 @@ matrix:
 
 dist: trusty
 
-before_cache:
-  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
-  # Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
-  # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
-  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
+before_install: |
+  if [ -n "$IS_OSX" ]; then
+      TAPS="$(brew --repository)/Library/Taps"
+      if [ -e "$TAPS/caskroom/homebrew-cask" -a -e "$TAPS/homebrew/homebrew-cask" ]; then
+          rm -rf "$TAPS/caskroom/homebrew-cask"
+      fi
+      find "$TAPS" -type d -name .git -exec \
+              bash -xec '
+                  cd $(dirname '\''{}'\'') || echo "status: $?"
+                  git clean -fxd || echo "status: $?"
+                  sleep 1 || echo "status: $?"
+                  git status || echo "status: $?"' \; || echo "status: $?"
+      brew_cache_cleanup
+  fi
+
+
+before_cache: |
+  # Cleanup dirs to be cached
+  set -e; set -x
+  if [ -n "$IS_OSX" ]; then
+      # When Taps is cached, this dir causes "Error: file exists" on `brew update`
+      if [ -e "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask" ]; then
+          rm -rf "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask"
+      fi
+      brew_cache_cleanup
+  fi
+  set +x; set +e
 
 #before_install:
 #  - brew upgrade pcl
